export const database = {
    collection : {
        item1 : {
            id: 'item1',
            fil: 'Bra',
            name: 'Vivisence 1035 Biustonosz push-up, beżowy',
            shortName : 'Vivisence 1035',
            type: 'Biustonosz push-up',
            img: require('../store/database/Vivisence_1035.jpg'),
            img2: require('../store/database/Vivisence_1035-2.jpg'),
            img3: require('../store/database/Vivisence_1035-3.jpg'),
            details : {
                opis : 'Specjalistyczny biustonosz typu push-up do zadań specjalnych. Idealna propozycja do kreacji z odkrytymi plecami. Biustonosz w całości wykonany jest z gładkiej mikrofibry. Model bez fiszbin bocznych. Druty podtrzymują i kształtują piersi. Niski mostek. Wyjmowane wkładki powiększające. Ramiączka regulowane, odpinane. Ramiączka silikonowe. Trzy możliwości krzyżowania ramiączek. Plastikowe haczyki do ramiączek. W tyle przezroczysty silikonowy pasek obniżający zapięcie. Plastikowe zapięcie z przodu. Między miseczkami subtelna ozdoba. Bielizna pakowana jest w eleganckie pudełko, doskonale nadaje się na prezent',
                sklad : '88% Polamid, 8% Bawełna, 4% Elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-1035-biustonosz-push-up-bezowy-5176.html?query_id=3#product_askforproduct',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Tak',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: plastikowe',
                    zapiecie : 'Miejsce zapięcia: przód',
                    kieszonki : 'Kieszonki na wkładki: Tak'
                },
            },
        },
        item2 : {
            id: 'item2',
            fil: 'Bra',
            name: 'Vivisence 1046 Biustonosz usztywniany, beżowy',
            shortName : 'Vivisence 1046',
            type: 'Biustonosz usztywniany',
            img: require('../store/database/Vivisence_1046.jpg'),
            img2: require('../store/database/Vivisence_1046-2.jpg'),
            img3: require('../store/database/Vivisence_1046-3.jpg'),
            details : {
                opis : 'Wyjątkowy usztywniany biustonosz typu "SPACER". Miseczki termincznie kształtowane, wykonane z wewnętrznej i zewnętrznej warstwy mikrofibry, między którymi istnieje przestrzeń, dająca lepszy przepływ potwietrza, co pozwala oddychać skórze. Ergonomiczny kształt miseczek idealnie dopasowuje biust. Miseczki gładkie, bezszwowe - nie odznaczają się pod odzieżą wierzchnią. Miseczki od wewnątrz (od strony pachy) wzmocnione warstwą tiulu stabilnego, który zabezpiecza przed zniekształceniem biustonosza w trakcie użytkowania oraz przenosi ciążar biustu do przodu, pięknie eksponując dekolt. Pomiędzy miseczkami i na górze miski delikatne kokardki. Mostek wykonany z tiulu, który stabilizuje miseczki. Boczki z mikrofibry dają wysoki komfort użytkowania, również przy dużych biustach. Ramiączka regulowane, nieodpinane. Metalowe haczyki do ramiączek. Trzyrzędowe zapięcie na haftki z trzystopniową regulacją. Konstrukcja SPACERA sprawia, że biustonosz idealnie nadaje się zarówno do codziennego użytkowania, jak i podczas uprawiania różnego typu aktywności sportowej. Bielizna pakowana jest w eleganckie pudełko, idealna propozycja na prezent',
                sklad : '90% poliamid, 10% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-1046-biustonosz-usztywniany-czarny-8718.html',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Nie',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: metalowe',
                    zapiecie : 'Miejsce zapięcia: tył',
                    kieszonki : 'Kieszonki na wkładki: Tak'
                },
            },
        },
        item3 : {
            id: 'item3',
            fil: 'Bra',
            name: 'Vivisence Eve 1012 Biustonosz specjalistyczny, beżowy',
            shortName : 'Vivisence Eve 1012',
            type: 'Biustonosz specjalistyczny',
            img: require('../store/database/Vivisence_1012.jpg'),
            img2: require('../store/database/Vivisence_1012-2.jpg'),
            img3: require('../store/database/Vivisence_1012-3.jpg'),
            details : {
                opis : 'Specjalistyczny biustonosz typu push-up do kreacji z odkrytymi plecami. Biustonosz w całości wykonany jest z gładkiej mikrofibry. Model bez fiszbin bocznych. Druty podtrzymują i kształtują piersi. Niski mostek. Wyjmowane wkładki powiększające. Ramiączka regulowane, odpinane. Ramiączka silikonowe. Metalowe haczyki do ramiączek. Z przodu plastikowe zapięcie. Z tyłu przezroczysta silikonowa taśma. Bielizna pakowana jest w eleganckie pudełko, doskonale nadaje się na prezent',
                sklad : '88% poliamid, 8% bawełna, 4% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-eve-1012-biustonosz-specjalistyczny-bezowy-2383.html',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Tak',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: metalowe',
                    zapiecie : 'Miejsce zapięcia: przód',
                    kieszonki : 'Kieszonki na wkładki: Tak'
                },
            },
        },
        item4 : {
            id: 'item4',
            fil: 'Bra',
            name: 'Vivisence 1045 Biustonosz półusztywniany, czarny',
            shortName : 'Vivisence 1045',
            type: 'Biustonosz półusztywniany',
            img: require('../store/database/Vivisence_1045.jpg'),
            img2: require('../store/database/Vivisence_1045-2.jpg'),
            img3: require('../store/database/Vivisence_1045-3.jpg'),
            details : {
                opis : 'Subtelny i niezwykle kobiecy biustonosz półusztywniany. Górna część miseczek wykonane są z połyskującej, kwiecistej koronki, podszytej siateczką. Dół miseczek wykonany jest z pianki gorseciarskiej pokrytej połyskującej koronką. Mostek i boczki wykonane z połyskującej koronki, podszytej siateczką. Między miseczkami urocza kokardka. Druty podtrzymują i kształtują piersi. Pionowe fiszbiny boczne. Ramiączka regulowane, nieodpinane. Metalowe haczyki do ramiączek. Plecy wykonane ze sprężystej, wzmocnionej siateczki. Dwurzędowe/trzystopniowe zapięcie na haftki z trzystopniową regulacją. Bielizna pakowana jest w eleganckie pudełko, doskonale nadaje się na prezent',
                sklad : '47% nylon, 21% poliamid, 14% bawełna, 12% elastan, 6% poliuretan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-1045-biustonosz-polusztywniany-czarny-7790.html?query_id=3',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Nie',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: metalowe',
                    zapiecie : 'Miejsce zapięcia: tył',
                    kieszonki : 'Kieszonki na wkładki: Brak'
                },
            },
        },
        item5 : {
            id: 'item5',
            fil: 'Bra',
            name: 'Vivisence 1035 Biustonosz push-up, beżowy',
            shortName : 'Vivisence 1035',
            type: 'Biustonosz push-up',
            img: require('../store/database/Vivisence_1035.jpg'),
            img2: require('../store/database/Vivisence_1035-2.jpg'),
            img3: require('../store/database/Vivisence_1035-3.jpg'),
            details : {
                opis : 'Specjalistyczny biustonosz typu push-up do zadań specjalnych. Idealna propozycja do kreacji z odkrytymi plecami. Biustonosz w całości wykonany jest z gładkiej mikrofibry. Model bez fiszbin bocznych. Druty podtrzymują i kształtują piersi. Niski mostek. Wyjmowane wkładki powiększające. Ramiączka regulowane, odpinane. Ramiączka silikonowe. Trzy możliwości krzyżowania ramiączek. Plastikowe haczyki do ramiączek. W tyle przezroczysty silikonowy pasek obniżający zapięcie. Plastikowe zapięcie z przodu. Między miseczkami subtelna ozdoba. Bielizna pakowana jest w eleganckie pudełko, doskonale nadaje się na prezent',
                sklad : '88% Polamid, 8% Bawełna, 4% Elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-1035-biustonosz-push-up-bezowy-5176.html?query_id=3#product_askforproduct',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Tak',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: plastikowe',
                    zapiecie : 'Miejsce zapięcia: przód',
                    kieszonki : 'Kieszonki na wkładki: Tak'
                },
            },
        },
        item6 : {
            id: 'item6',
            fil: 'Bra',
            name: 'Vivisence 1046 Biustonosz usztywniany, beżowy',
            shortName : 'Vivisence 1046',
            type: 'Biustonosz usztywniany',
            img: require('../store/database/Vivisence_1046.jpg'),
            img2: require('../store/database/Vivisence_1046-2.jpg'),
            img3: require('../store/database/Vivisence_1046-3.jpg'),
            details : {
                opis : 'Wyjątkowy usztywniany biustonosz typu "SPACER". Miseczki termincznie kształtowane, wykonane z wewnętrznej i zewnętrznej warstwy mikrofibry, między którymi istnieje przestrzeń, dająca lepszy przepływ potwietrza, co pozwala oddychać skórze. Ergonomiczny kształt miseczek idealnie dopasowuje biust. Miseczki gładkie, bezszwowe - nie odznaczają się pod odzieżą wierzchnią. Miseczki od wewnątrz (od strony pachy) wzmocnione warstwą tiulu stabilnego, który zabezpiecza przed zniekształceniem biustonosza w trakcie użytkowania oraz przenosi ciążar biustu do przodu, pięknie eksponując dekolt. Pomiędzy miseczkami i na górze miski delikatne kokardki. Mostek wykonany z tiulu, który stabilizuje miseczki. Boczki z mikrofibry dają wysoki komfort użytkowania, również przy dużych biustach. Ramiączka regulowane, nieodpinane. Metalowe haczyki do ramiączek. Trzyrzędowe zapięcie na haftki z trzystopniową regulacją. Konstrukcja SPACERA sprawia, że biustonosz idealnie nadaje się zarówno do codziennego użytkowania, jak i podczas uprawiania różnego typu aktywności sportowej. Bielizna pakowana jest w eleganckie pudełko, idealna propozycja na prezent',
                sklad : '90% poliamid, 10% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-1046-biustonosz-usztywniany-czarny-8718.html',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Nie',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: metalowe',
                    zapiecie : 'Miejsce zapięcia: tył',
                    kieszonki : 'Kieszonki na wkładki: Tak'
                },
            },
        },
        item7 : {
            id: 'item7',
            fil: 'Bra',
            name: 'Vivisence Eve 1012 Biustonosz specjalistyczny, beżowy',
            shortName : 'Vivisence Eve 1012',
            type: 'Biustonosz specjalistyczny',
            img: require('../store/database/Vivisence_1012.jpg'),
            img2: require('../store/database/Vivisence_1012-2.jpg'),
            img3: require('../store/database/Vivisence_1012-3.jpg'),
            details : {
                opis : 'Specjalistyczny biustonosz typu push-up do kreacji z odkrytymi plecami. Biustonosz w całości wykonany jest z gładkiej mikrofibry. Model bez fiszbin bocznych. Druty podtrzymują i kształtują piersi. Niski mostek. Wyjmowane wkładki powiększające. Ramiączka regulowane, odpinane. Ramiączka silikonowe. Metalowe haczyki do ramiączek. Z przodu plastikowe zapięcie. Z tyłu przezroczysta silikonowa taśma. Bielizna pakowana jest w eleganckie pudełko, doskonale nadaje się na prezent',
                sklad : '88% poliamid, 8% bawełna, 4% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-eve-1012-biustonosz-specjalistyczny-bezowy-2383.html',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Tak',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: metalowe',
                    zapiecie : 'Miejsce zapięcia: przód',
                    kieszonki : 'Kieszonki na wkładki: Tak'
                },
            },
        },
        item8 : {
            id: 'item8',
            fil: 'Bra',
            name: 'Vivisence 1045 Biustonosz półusztywniany, czarny',
            shortName : 'Vivisence 1045',
            type: 'Biustonosz półusztywniany',
            img: require('../store/database/Vivisence_1045.jpg'),
            img2: require('../store/database/Vivisence_1045-2.jpg'),
            img3: require('../store/database/Vivisence_1045-3.jpg'),
            details : {
                opis : 'Subtelny i niezwykle kobiecy biustonosz półusztywniany. Górna część miseczek wykonane są z połyskującej, kwiecistej koronki, podszytej siateczką. Dół miseczek wykonany jest z pianki gorseciarskiej pokrytej połyskującej koronką. Mostek i boczki wykonane z połyskującej koronki, podszytej siateczką. Między miseczkami urocza kokardka. Druty podtrzymują i kształtują piersi. Pionowe fiszbiny boczne. Ramiączka regulowane, nieodpinane. Metalowe haczyki do ramiączek. Plecy wykonane ze sprężystej, wzmocnionej siateczki. Dwurzędowe/trzystopniowe zapięcie na haftki z trzystopniową regulacją. Bielizna pakowana jest w eleganckie pudełko, doskonale nadaje się na prezent',
                sklad : '47% nylon, 21% poliamid, 14% bawełna, 12% elastan, 6% poliuretan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-1045-biustonosz-polusztywniany-czarny-7790.html?query_id=3',
                info : {
                    pranie : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    ramiaczkaRe : 'Ramiączka regulowane : Tak',
                    ramiaczkaOd : 'Ramiączka odpinane: Nie',
                    druty : 'Druty : Tak',
                    haczyki : 'Haczyki do ramiączek: metalowe',
                    zapiecie : 'Miejsce zapięcia: tył',
                    kieszonki : 'Kieszonki na wkładki: Brak'
                },
            },
        },
        item9 : {
            id: 'item9',
            fil: 'Nightwear',
            name: 'Babella Monica Nocna koszulka, czerwony',
            shortName : 'Babella Monica',
            type: 'Koszula nocna',
            img: require('../store/database/Babella_Monica.jpg'),
            img2: require('../store/database/Babella_Monica-2.jpg'),
            img3: require('../store/database/Babella_Monica-3.jpg'),
            details : {
                opis : 'Elegancka i niezwykle kobieca koszulka nocna. Klasyczny krój. Cienkie, regulowane ramiączka. Subtelne marszczenia na biuście. Dekolt i boki zdobią koronkowe wstawki. Przyjemna w dotyku wiskoza',
                sklad : '88% Polamid, 8% Bawełna, 4% Elastan',
                redirect : 'https://www.kontri.pl/pl/products/babella-monica-nocna-koszulka-czerwony-22696.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: czerwony',
                    3 : 'Kolor podstawowy: czerwony',
                    4 : 'Model: Monica',
                    5 : 'Ramiączka Regulowane: TAK',
                    6 : 'Długość: mini',
                    7 : 'Rodzaj dekoltu: szpic',
                    8 : 'Kategoria: Koszulka nocna'
                },
            },
        },
        item10 : {
            id: 'item10',
            fil: 'Nightwear',
            name: 'Babella Miranda Nocna koszulka, różowy',
            shortName : 'Babella Miranda',
            type: 'Koszula nocna',
            img: require('../store/database/Babella_Miranda.jpg'),
            img2: require('../store/database/Babella_Miranda-2.jpg'),
            img3: require('../store/database/Babella_Miranda-3.jpg'),
            details : {
                opis : 'Elegancka koszulka nocna Miranda. Dopasowany krój podkreśla kobiece kształty. Cienkie, regulowane ramiączka. Dekolt w szpic. Dekolt pokryty koronką. Koronkowe wstawki w talii tworzą sylwetkę klepsydry. Przyjemna w dotyku wiskoza.',
                sklad : '94% wiskoza, 6% elastan',
                redirect : 'https://www.kontri.pl/pl/products/babella-miranda-nocna-koszulka-rozowy-22698.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: różowy',
                    3 : 'Kolor podstawowy: różowy',
                    4 : 'Model: Miranda',
                    5 : 'Ramiączka Regulowane: TAK',
                    6 : 'Długość: mini',
                    7 : 'Rodzaj dekoltu: szpic',
                    8 : 'Kategoria: Koszulka nocna'
                },
            },
        },
        item11 : {
            id: 'item11',
            fil: 'Nightwear',
            name: 'Babella Magnolia Nocna koszulka, druk/czarny',
            shortName : 'Babella Magnolia',
            type: 'Koszula nocna',
            img: require('../store/database/Babella_Magnolia.jpg'),
            img2: require('../store/database/Babella_Magnolia-2.jpg'),
            img3: require('../store/database/Babella_Magnolia-3.jpg'),
            details : {
                opis : 'Lekka i zwiewna koszulka nocna w piękne kwiaty. Krój A. Dekolt w szpic, wykończony koronką. Cienkie, regulowane ramiączka. Przyjemna w dotyku wiskoza. Do kompletu polecamy szlafrok Magnolia. Koszula została uszyta w Polsce.',
                sklad : '94% wiskoza, 6% elastan',
                redirect : 'https://www.kontri.pl/pl/products/babella-magnolia-nocna-koszulka-druk-czarny-22478.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: druk/czarny',
                    3 : 'Kolor podstawowy: czarny',
                    4 : 'Model: Magnolia',
                    5 : 'Ramiączka Regulowane: TAK',
                    6 : 'Długość rękawa: na ramiączkach',
                    7 : 'Kategoria: Koszulka nocna'
                },
            },
        },
        item12 : {
            id: 'item12',
            fil: 'Nightwear',
            name: 'Italian Fashion Song ws.r. Nocna koszula, granat',
            shortName : 'Italian Fashion Song',
            type: 'Koszula nocna',
            img: require('../store/database/Italian_Fashion_Song.jpg'),
            img2: require('../store/database/Italian_Fashion_Song-2.jpg'),
            img3: require('../store/database/Italian_Fashion_Song-3.jpg'),
            details : {
                opis : 'Subtelna i bardzo kobieca koszula Song. Klasyczny krój. Wąskie ramiączka. Dekolt „V”. Gładka, miła w dotyku wiskoza. Zaprojektowana i uszyta w Polsce',
                sklad : '90% wiskoza, 10% elastan',
                redirect : 'https://www.kontri.pl/pl/products/italian-fashion-song-ws-r-nocna-koszula-granat-22886.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: granat',
                    3 : 'Kolor podstawowy: granat',
                    4 : 'Model: Song ws.r.',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Długość rękawa: na ramiączkach',
                    7 : 'Rodzaj dekoltu: szpic',
                    8 : 'Kategoria: Koszulka nocna'
                },
            },
        },
        item13 : {
            id: 'item13',
            fil: 'Nightwear',
            name: 'Babella Monica Nocna koszulka, czerwony',
            shortName : 'Babella Monica',
            type: 'Koszula nocna',
            img: require('../store/database/Babella_Monica.jpg'),
            img2: require('../store/database/Babella_Monica-2.jpg'),
            img3: require('../store/database/Babella_Monica-3.jpg'),
            details : {
                opis : 'Elegancka i niezwykle kobieca koszulka nocna. Klasyczny krój. Cienkie, regulowane ramiączka. Subtelne marszczenia na biuście. Dekolt i boki zdobią koronkowe wstawki. Przyjemna w dotyku wiskoza',
                sklad : '88% Polamid, 8% Bawełna, 4% Elastan',
                redirect : 'https://www.kontri.pl/pl/products/babella-monica-nocna-koszulka-czerwony-22696.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: czerwony',
                    3 : 'Kolor podstawowy: czerwony',
                    4 : 'Model: Monica',
                    5 : 'Ramiączka Regulowane: TAK',
                    6 : 'Długość: mini',
                    7 : 'Rodzaj dekoltu: szpic',
                    8 : 'Kategoria: Koszulka nocna'
                },
            },
        },
        item14 : {
            id: 'item14',
            fil: 'Nightwear',
            name: 'Babella Miranda Nocna koszulka, różowy',
            shortName : 'Babella Miranda',
            type: 'Koszula nocna',
            img: require('../store/database/Babella_Miranda.jpg'),
            img2: require('../store/database/Babella_Miranda-2.jpg'),
            img3: require('../store/database/Babella_Miranda-3.jpg'),
            details : {
                opis : 'Elegancka koszulka nocna Miranda. Dopasowany krój podkreśla kobiece kształty. Cienkie, regulowane ramiączka. Dekolt w szpic. Dekolt pokryty koronką. Koronkowe wstawki w talii tworzą sylwetkę klepsydry. Przyjemna w dotyku wiskoza.',
                sklad : '94% wiskoza, 6% elastan',
                redirect : 'https://www.kontri.pl/pl/products/babella-miranda-nocna-koszulka-rozowy-22698.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: różowy',
                    3 : 'Kolor podstawowy: różowy',
                    4 : 'Model: Miranda',
                    5 : 'Ramiączka Regulowane: TAK',
                    6 : 'Długość: mini',
                    7 : 'Rodzaj dekoltu: szpic',
                    8 : 'Kategoria: Koszulka nocna'
                },
            },
        },
        item15 : {
            id: 'item15',
            fil: 'Nightwear',
            name: 'Babella Magnolia Nocna koszulka, druk/czarny',
            shortName : 'Babella Magnolia',
            type: 'Koszula nocna',
            img: require('../store/database/Babella_Magnolia.jpg'),
            img2: require('../store/database/Babella_Magnolia-2.jpg'),
            img3: require('../store/database/Babella_Magnolia-3.jpg'),
            details : {
                opis : 'Lekka i zwiewna koszulka nocna w piękne kwiaty. Krój A. Dekolt w szpic, wykończony koronką. Cienkie, regulowane ramiączka. Przyjemna w dotyku wiskoza. Do kompletu polecamy szlafrok Magnolia. Koszula została uszyta w Polsce.',
                sklad : '94% wiskoza, 6% elastan',
                redirect : 'https://www.kontri.pl/pl/products/babella-magnolia-nocna-koszulka-druk-czarny-22478.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: druk/czarny',
                    3 : 'Kolor podstawowy: czarny',
                    4 : 'Model: Magnolia',
                    5 : 'Ramiączka Regulowane: TAK',
                    6 : 'Długość rękawa: na ramiączkach',
                    7 : 'Kategoria: Koszulka nocna'
                },
            },
        },
        item16 : {
            id: 'item16',
            fil: 'Nightwear',
            name: 'Italian Fashion Song ws.r. Nocna koszula, granat',
            shortName : 'Italian Fashion Song',
            type: 'Koszula nocna',
            img: require('../store/database/Italian_Fashion_Song.jpg'),
            img2: require('../store/database/Italian_Fashion_Song-2.jpg'),
            img3: require('../store/database/Italian_Fashion_Song-3.jpg'),
            details : {
                opis : 'Subtelna i bardzo kobieca koszula Song. Klasyczny krój. Wąskie ramiączka. Dekolt „V”. Gładka, miła w dotyku wiskoza. Zaprojektowana i uszyta w Polsce',
                sklad : '90% wiskoza, 10% elastan',
                redirect : 'https://www.kontri.pl/pl/products/italian-fashion-song-ws-r-nocna-koszula-granat-22886.html',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: granat',
                    3 : 'Kolor podstawowy: granat',
                    4 : 'Model: Song ws.r.',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Długość rękawa: na ramiączkach',
                    7 : 'Rodzaj dekoltu: szpic',
                    8 : 'Kategoria: Koszulka nocna'
                },
            },
        },







        item17 : {
            id: 'item17',
            fil : 'Swimmwear',
            name: 'Vivisence 3108 Kostium kąpielowy jednoczęściowy, czarny',
            shortName : 'Vivisence 3108',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Vivisence_3108.jpg'),
            img2: require('../store/database/Vivisence_3108-2.jpg'),
            img3: require('../store/database/Vivisence_3108-3.jpg'),
            details : {
                opis : 'Klasyczny jednoczęściowy kostium kąpielowy. Usztywniane miseczki. Dekolt w serek. Między miseczkami kokardka. Druty podtrzymują i kształtują piersi. Przód podszyty jest dodatkową dzianiną. Z tyłu wygodne zapięcie na klamerkę. Szersze, regulowane, nieodpinane ramiączka. Dzięki marszczeniom kostium doskonale zatuszuje niedoskonałości w okolicach brzuszka. Wykonany jest z wysokiej jakości dzianiny. Zwiększona odporność na odbarwienia i zniekształcenia',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-3108-kostium-kapielowy-jednoczesciowy-czarny-20412.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: czarny',
                    3 : 'Kolor podstawowy: czarny',
                    4 : 'Model: 3108',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },
        item18 : {
            id: 'item18',
            fil : 'Swimmwear',
            name: 'Ava SK-140 MAXI Kostium kąpielowy biustonosz miękki, emerald',
            shortName : 'Ava SK-140',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Ava_SK-140.jpg'),
            img2: require('../store/database/Ava_SK-140-2.jpg'),
            img3: require('../store/database/Ava_SK-140-3.jpg'),
            details : {
                opis : 'Biustonosz kąpielowy typu soft. Z połyskującej mikrofibry. Miękkie miseczki z fiszbinami. Wygodne ramiączka dopasowane do wielkości rozmiaru. Idealny komplet z figami kąpielowymi SF 140/3',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/ava-sk-140-maxi-kostium-kapielowy-biustonosz-miekki-emerald-21062.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: emerald',
                    3 : 'Kolor podstawowy: zielony',
                    4 : 'Model: SK-140',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },
        item19 : {
            id: 'item19',
            fil : 'Swimmwear',
            name: 'Vivisence 3108 Kostium kąpielowy jednoczęściowy, czarny',
            shortName : 'Vivisence 3108',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Vivisence_3108.jpg'),
            img2: require('../store/database/Vivisence_3108-2.jpg'),
            img3: require('../store/database/Vivisence_3108-3.jpg'),
            details : {
                opis : 'Klasyczny jednoczęściowy kostium kąpielowy. Usztywniane miseczki. Dekolt w serek. Między miseczkami kokardka. Druty podtrzymują i kształtują piersi. Przód podszyty jest dodatkową dzianiną. Z tyłu wygodne zapięcie na klamerkę. Szersze, regulowane, nieodpinane ramiączka. Dzięki marszczeniom kostium doskonale zatuszuje niedoskonałości w okolicach brzuszka. Wykonany jest z wysokiej jakości dzianiny. Zwiększona odporność na odbarwienia i zniekształcenia',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-3108-kostium-kapielowy-jednoczesciowy-czarny-20412.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: czarny',
                    3 : 'Kolor podstawowy: czarny',
                    4 : 'Model: 3108',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },
        item20 : {
            id: 'item20',
            fil : 'Swimmwear',
            name: 'Ava SK-140 MAXI Kostium kąpielowy biustonosz miękki, emerald',
            shortName : 'Ava SK-140',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Ava_SK-140.jpg'),
            img2: require('../store/database/Ava_SK-140-2.jpg'),
            img3: require('../store/database/Ava_SK-140-3.jpg'),
            details : {
                opis : 'Biustonosz kąpielowy typu soft. Z połyskującej mikrofibry. Miękkie miseczki z fiszbinami. Wygodne ramiączka dopasowane do wielkości rozmiaru. Idealny komplet z figami kąpielowymi SF 140/3',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/ava-sk-140-maxi-kostium-kapielowy-biustonosz-miekki-emerald-21062.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: emerald',
                    3 : 'Kolor podstawowy: zielony',
                    4 : 'Model: SK-140',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },
        item21 : {
            id: 'item21',
            fil : 'Swimmwear',
            name: 'Vivisence 3108 Kostium kąpielowy jednoczęściowy, czarny',
            shortName : 'Vivisence 3108',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Vivisence_3108.jpg'),
            img2: require('../store/database/Vivisence_3108-2.jpg'),
            img3: require('../store/database/Vivisence_3108-3.jpg'),
            details : {
                opis : 'Klasyczny jednoczęściowy kostium kąpielowy. Usztywniane miseczki. Dekolt w serek. Między miseczkami kokardka. Druty podtrzymują i kształtują piersi. Przód podszyty jest dodatkową dzianiną. Z tyłu wygodne zapięcie na klamerkę. Szersze, regulowane, nieodpinane ramiączka. Dzięki marszczeniom kostium doskonale zatuszuje niedoskonałości w okolicach brzuszka. Wykonany jest z wysokiej jakości dzianiny. Zwiększona odporność na odbarwienia i zniekształcenia',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-3108-kostium-kapielowy-jednoczesciowy-czarny-20412.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: czarny',
                    3 : 'Kolor podstawowy: czarny',
                    4 : 'Model: 3108',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },
        item22 : {
            id: 'item22',
            fil : 'Swimmwear',
            name: 'Ava SK-140 MAXI Kostium kąpielowy biustonosz miękki, emerald',
            shortName : 'Ava SK-140',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Ava_SK-140.jpg'),
            img2: require('../store/database/Ava_SK-140-2.jpg'),
            img3: require('../store/database/Ava_SK-140-3.jpg'),
            details : {
                opis : 'Biustonosz kąpielowy typu soft. Z połyskującej mikrofibry. Miękkie miseczki z fiszbinami. Wygodne ramiączka dopasowane do wielkości rozmiaru. Idealny komplet z figami kąpielowymi SF 140/3',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/ava-sk-140-maxi-kostium-kapielowy-biustonosz-miekki-emerald-21062.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: emerald',
                    3 : 'Kolor podstawowy: zielony',
                    4 : 'Model: SK-140',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },
        item23 : {
            id: 'item23',
            fil : 'Swimmwear',
            name: 'Vivisence 3108 Kostium kąpielowy jednoczęściowy, czarny',
            shortName : 'Vivisence 3108',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Vivisence_3108.jpg'),
            img2: require('../store/database/Vivisence_3108-2.jpg'),
            img3: require('../store/database/Vivisence_3108-3.jpg'),
            details : {
                opis : 'Klasyczny jednoczęściowy kostium kąpielowy. Usztywniane miseczki. Dekolt w serek. Między miseczkami kokardka. Druty podtrzymują i kształtują piersi. Przód podszyty jest dodatkową dzianiną. Z tyłu wygodne zapięcie na klamerkę. Szersze, regulowane, nieodpinane ramiączka. Dzięki marszczeniom kostium doskonale zatuszuje niedoskonałości w okolicach brzuszka. Wykonany jest z wysokiej jakości dzianiny. Zwiększona odporność na odbarwienia i zniekształcenia',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/vivisence-3108-kostium-kapielowy-jednoczesciowy-czarny-20412.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: czarny',
                    3 : 'Kolor podstawowy: czarny',
                    4 : 'Model: 3108',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },
        item24 : {
            id: 'item24',
            fil : 'Swimmwear',
            name: 'Ava SK-140 MAXI Kostium kąpielowy biustonosz miękki, emerald',
            shortName : 'Ava SK-140',
            type: 'Kostium kąpielowy',
            img: require('../store/database/Ava_SK-140.jpg'),
            img2: require('../store/database/Ava_SK-140-2.jpg'),
            img3: require('../store/database/Ava_SK-140-3.jpg'),
            details : {
                opis : 'Biustonosz kąpielowy typu soft. Z połyskującej mikrofibry. Miękkie miseczki z fiszbinami. Wygodne ramiączka dopasowane do wielkości rozmiaru. Idealny komplet z figami kąpielowymi SF 140/3',
                sklad : '80% poliamid, 20% elastan',
                redirect : 'https://www.kontri.pl/pl/products/ava-sk-140-maxi-kostium-kapielowy-biustonosz-miekki-emerald-21062.html?query_id=6',
                info : {
                    0 : 'Tylko pranie ręczne, nie czyścić chemicznie, nie wybielać, nie prasować, nie suszyć w suszarce.',
                    1 : 'Płeć kupującego: Kobieta',
                    2 : 'Kolor: emerald',
                    3 : 'Kolor podstawowy: zielony',
                    4 : 'Model: SK-140',
                    5 : 'Ramiączka Regulowane: NIE',
                    6 : 'Druty : TAK',
                    7 : 'Rodzaj zapięcia : klamerka',
                    8 : 'Kategoria: Kostium kąpielowy'
                },
            },
        },

    }
        
    }

